### PR TITLE
Updating axe, fixing tests, etc.

### PR DESCRIPTION
**Pull request by jjaquish**

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@jjaquish @mshriver hello from the otherside! I was updating my Github Organizations and stumbled into repo. Just a FYI, the Ansible Tower team has done quite a bit of work on a11y testing and patternfly. I'd reach out to them while continuing on an a11y journey.

The https://github.com/patternfly/patternfly-a11y should do almost everything you'd need in addition to reporting.

**Comment by john-dupuy** [comment]
Greetings @unlikelyzero! o/

We looked a bit into `patternfly-a11y` and then stumbled across this repo and https://github.com/mozilla-services/pytest-axe/ which we thought may provide easier integration with our existing IQE UI testing stack (`navmazing`/`pytest`).

We definitely don't want to reinvent the wheel here though, especially around the reporting, etc that patternfly-a11y already provides, so thanks for mentioning this!

**Review by john-dupuy — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@john-dupuy I'm glad you found the repo. We had stumbled into it on own journey by chance. We also stumbled into two slack chatrooms: coreOS #a11y and patternflys #a11y

Tiago Silva is now leading the a11y efforts on Ansible QE and it would be great if you all traded notes. Specifically, he was working on integrating Cypress a11y json dumps into the patternfly-a11y reporting. It might be possible for pytest-axe to do the same 

One problem with using axe is that it cannot be run with strict CSP. We had to disable all of our a11y tests which ran against prod. He may have found other technical limitations recently.

Anyways, wish you all the best.

**Comment by jjaquish** [comment]
@unlikelyzero Thanks for all of the information! We'll definitely check out those chat rooms and reach out to Tiago Silva for to discuss further.

**Pull request merged**
